version: '3.8'

services:

  web:
    build: .
    ports:
      - 8004:8000
    command: uvicorn api:app --host 0.0.0.0 --reload
    volumes:
      - ./project:/usr/src/app
    env_file:
      - .env.test
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
  
  worker:
    build: .
    command: celery -A worker.celery worker --loglevel=info
    volumes:
      - ./project:/usr/src/app
    env_file:
      - .env.test
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - web

  redis:
    image: redis:7
