version: '3.8'

services:

  web:
    build: .
    ports:
      - 8004:8000
    command: uvicorn api:app --host 0.0.0.0 --reload
    volumes:
      - ./project:/usr/src/app
    env_file:
      - .env
