version: '3.8'

services:

  api:
    build: .
    ports:
      - 8004:8000
    command: uvicorn app:fastapi --host 0.0.0.0 --reload
    working_dir: /code/src
    volumes:
      - ./src:/code/src
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  worker:
    build: .
    command: celery -A worker.celery worker --loglevel=info -B
    working_dir: /code/src
    volumes:
      - ./src:/code/src
    env_file:
      - .env
    depends_on:
      - redis
      - api
      - postgres

  redis:
    image: redis:7

  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:z
    user: 1000:1000
    env_file:
      - .env
